#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "diaspora"
name = "Diaspora"
description.en = "Distributed social networking service"
description.fr = "Service de réseau social distribué"

version = "0.9.0.0~ynh1"

maintainers = ["autra"]

[upstream]
license = "AGPL-3.0"
website = "https://diasporafoundation.org/"
admindoc = "https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers"
userdoc = "https://wiki.diasporafoundation.org/FAQ_for_users"
code = "https://github.com/diaspora/diaspora"

[integration]
yunohost = ">=11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Admin password. Must contain at least 10 characters, one lowercase letter, one uppercase letter, one number, and one symbol (e.g. '~!@#$%^&*()')."
    help.fr = "Mot de passe pour l’administrateur. Doit contenir au moins 10 caractères, une majuscule, une minuscule, un chiffre, et une ponctuation (ex. '~!@#$%^&*()')."
    type = "password"
    optional = false

[resources]
    [resources.sources.main]
    url = "https://github.com/diaspora/diaspora/archive/refs/tags/v0.9.0.0.tar.gz"
    sha256 = "11c79d8cc86412f0a94de62f5a8cc115428d978333c6129c96bbf44f39adc31d"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "build-essential",
        "curl",
        "gsfonts",
        "imagemagick",
        "libmagickwand-dev",
        "redis-server",
        "libssl-dev",
        "libcurl4-openssl-dev",
        "libxml2-dev",
        "libxslt1-dev",
        "libidn11-dev",
        "libpq-dev",

        "postgresql",

        # Is it still required?
        "cmake",
        "ghostscript",
        "libffi-dev",
        "libgdbm-dev",
        "libncurses5-dev",
        "libyaml-dev",
        "pkg-config",
        "sqlite3",
        "libgmp-dev",
        # For Ruby
        "libjemalloc-dev",
        "libreadline-dev",
        "zlib1g-dev",
        "libsqlite3-dev",
        "libxslt-dev",
        "autoconf",
        "automake",
        "bison",
        "libtool",
    ]

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]

    [resources.database]
    type = "postgresql"
