#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "diaspora"
name = "Diaspora"
description.en = "Distributed social networking service"
description.fr = "Service de réseau social distribué"

version = "0.7.18.2~ynh3"

maintainers = ["autra"]

[upstream]
license = "AGPL-3.0"
website = "https://diasporafoundation.org/"
admindoc = "https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers"
userdoc = "https://wiki.diasporafoundation.org/FAQ_for_users"
code = "https://github.com/diaspora/diaspora"

[integration]
yunohost = ">=11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Admin password. Must contain at least 10 characters, one lowercase letter, one uppercase letter, one number, and one symbol (e.g. '~!@#$%^&*()')."
    help.fr = "Mot de passe pour l’administrateur. Doit contenir au moins 10 caractères, une majuscule, une minuscule, un chiffre, et une ponctuation (ex. '~!@#$%^&*()')."
    type = "password"
    optional = false

[resources]
    [resources.sources.main]
    url = "https://github.com/diaspora/diaspora/archive/refs/tags/v0.7.18.2.tar.gz"
    sha256 = "0b5828aa45af2361bfda4cd0f1e97070c322d90f1d16416bae2cba2418af9930"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "cmake",
        "imagemagick",
        "ghostscript",
        "curl",
        "libmagickwand-dev",
        "git",
        "libpq-dev",
        "redis-server",
        "postgresql",
        "libffi-dev",
        "libgdbm-dev",
        "libncurses5-dev",
        "libyaml-dev",
        "pkg-config",
        "sqlite3",
        "libgmp-dev",
        "libssl-dev",
        # For Ruby
        "libjemalloc-dev",
        "curl",
        "build-essential",
        "libreadline-dev",
        "zlib1g-dev",
        "libsqlite3-dev",
        "libssl-dev",
        "libxml2-dev",
        "libxslt-dev",
        "autoconf",
        "automake",
        "bison",
        "libtool",
    ]

    [resources.database]
    type = "postgresql"
