#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing Ruby..."
ynh_ruby_install

ynh_script_progression "Installing NodeJS..."
ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/live"

mkdir -p "$install_dir/uploads"
ln -s "$install_dir/uploads" "$install_dir/live/public"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration file..."

ynh_config_add --template="diaspora.toml" --destination="$install_dir/live/config/diaspora.toml"

ynh_config_add --template="database.yml" --destination="$install_dir/live/config/database.yml"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir/live"
  gem install "bundler:$bundler_version"
  ynh_hide_warnings ynh_exec_as_app "$ld_preload" script/configure_bundler
  ynh_hide_warnings ynh_exec_as_app "$ld_preload" bin/bundle install --full-index --with=postgresql
  ynh_hide_warnings ynh_exec_as_app RAILS_ENV=production bin/bundle exec rake db:migrate
  ynh_hide_warnings ynh_exec_as_app RAILS_ENV=production "$ld_preload" bin/rake assets:precompile
  ynh_hide_warnings ynh_exec_as_app RAILS_ENV=production "$ld_preload" bin/bundle exec rails console << END
user = User.build({username: '$admin', email: '$admin_mail', password: '$password', password_confirmation: '$password' })
user.save
user.seed_aspects
Role.add_admin user.person
END
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}_sidekiq" --template="diaspora_sidekiq.service"
ynh_config_add_systemd --service="${app}_web" --template="diaspora_web.service"

# Create target unit
_ynh_add_systemd_target
yunohost service add "$app.target" --description "Diaspora service (web and sidekiq)" \
  --log "$install_dir/live/log/production.log" \
        "$install_dir/live/log/web-stderr.log" \
        "$install_dir/live/log/web-stdout.log" \
        "$install_dir/live/log/sidekiq.log"

# Create tmpfile
ynh_config_add --template="diaspora.tmpfiles.d" --destination="/etc/tmpfiles.d/${app}.conf"
systemd-tmpfiles --create

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

systemctl restart "${app}.target"
ynh_systemctl --service="${app}_web.service" --action=restart --log_path="$install_dir/live/log/production.log" --wait_until="successfully configured the federation library"
ynh_systemctl --service="${app}_sidekiq.service" --action=restart --log_path="systemd" --wait_until="Running in ruby"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
