#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app.target" >/dev/null; then
	yunohost service remove "$app.target"
fi
ynh_config_remove_systemd

ynh_safe_rm "/etc/tmpfiles.d/${app}.conf"
ynh_safe_rm "/run/${app}"

_ynh_remove_systemd_target

ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
