#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Reinstalling Ruby..." --weight=5
ynh_exec_warn_less ynh_install_ruby --ruby_version="$ruby_version"

ynh_script_progression --message="Reinstalling NodeJS..." --weight=5
ynh_exec_warn_less ynh_install_nodejs --nodejs_version="$nodejs_version"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression --message="Restoring the PostgreSQL database..." --weight=1

ynh_psql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./db.sql

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..." --weight=40

pushd "$install_dir/live"
  ynh_use_ruby
  ynh_use_nodejs
  ynh_gem install "bundler:$bundler_version"
  ynh_exec_as "$app" "$ynh_ruby_load_path" "$ld_preload" script/configure_bundler
popd

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/systemd/system/${app}_web.service"
ynh_restore_file --origin_path="/etc/systemd/system/${app}_sidekiq.service"
ynh_restore_file --origin_path="/etc/systemd/system/${app}.target"
systemctl enable "${app}_web" "${app}_sidekiq" "$app.target" --quiet
yunohost service add "$app.target" --description "Diaspora service (web and sidekiq)" \
  --log "$install_dir/live/log/production.log" \
        "$install_dir/live/log/web-stderr.log" \
        "$install_dir/live/log/web-stdout.log" \
        "$install_dir/live/log/sidekiq.log"

ynh_restore_file --origin_path="/etc/tmpfiles.d/${app}.conf"
systemd-tmpfiles --create

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

systemctl restart "${app}.target"
ynh_systemd_action --service_name="${app}_web.service" --action=restart --log_path="$install_dir/live/log/production.log" --line_match="successfully configured the federation library"
ynh_systemd_action --service_name="${app}_sidekiq.service" --action=restart --log_path="systemd" --line_match="Running in ruby"

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
